name: POP - poutine on poutine

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/**
      - action.yml
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/**
      - action.yml

permissions:
  security-events: write
  contents: read

jobs:
  pop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        path: itself
    - uses: ./
      with:
        path: itself
